name: Build

on:
  - push
  - pull_request

jobs:
  build:
    name: Splunk AppInspect
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Splunk AppInspect CLI
        run: pip install splunk-appinspect

      - run: make splunk_heroku_log_drain-latest.tar.gz

      - name: Run splunk-appinspect inspect
        run: splunk-appinspect inspect --included-tags cloud --max-messages all splunk_heroku_log_drain-latest.tar.gz
