name: Build

on:
  - push
  - pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make splunk_heroku-latest.tar.gz
      - uses: actions/upload-artifact@v3
        with:
          name: splunk_heroku-latest.tar.gz
          path: splunk_heroku-latest.tar.gz

  splunk_appinspect:
    name: Splunk AppInspect
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: splunk_heroku-latest.tar.gz

      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Splunk AppInspect
        run: pip install splunk-appinspect

      - name: Run splunk-appinspect inspect
        run: splunk-appinspect inspect --included-tags cloud --max-messages all splunk_heroku-latest.tar.gz

  slim:
    name: Splunk Packaging Toolkit
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: splunk_heroku-latest.tar.gz

      # Splunk Packaging Toolkit version 1.0.1 doesn't work with Python 3.10
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install Splunk Packaging Toolkit
        run: pip install splunk-packaging-toolkit

      - name: Run slim validate
        run: slim validate splunk_heroku-latest.tar.gz
